tap homebrew/dupes
update
tap homebrew/versions
tap homebrew/services
tap thoughtbot/formulae
install apple-gcc48
install ssh-copy-id
install python
install mysql
install postgresql
install qt
install openssl
install ctags
install git
install imagemagick
install phantomjs
install chruby
install ruby-install
install tmux
install tmate
install wget
install the_silver_searcher
install vim --override-system-v
install neovim/neovim/neovim
install gitsh
install hub
install redis
install sphinx
install rcm
install terminal-notifier
install reattach-to-user-namespace
install ghostscript
install aspell
install ansible
install nvm
install httpie
install ack
install gpg
install keybase
install tree
install awsebcli
tap iveney/mocha
install realpath
install exiftool
install poppler
install task
install taskd
install tasksh
