update
tap homebrew/dupes
tap homebrew/versions
tap thoughtbot/formulae
install apple-gcc48
install ssh-copy-id
install python
install mysql
install postgresql
install qt
install openssl
install node
install ctags
install git
install imagemagick
install phantomjs
install chruby
install ruby-install
install tmux
install wget
install the_silver_searcher
install vim --override-system-v
install gitsh
install hub
install redis
install sphinx
install rcm
install terminal-notifier
install reattach-to-user-namespace
install ghostscript
install aspell
install ansible
install boot2docker
install nvm
