brew update
tap homebrew/services
tap thoughtbot/formulae
tap iveney/mocha
install apple-gcc48
install ssh-copy-id
install openssl
install git
install imagemagick
install tmux
install wget
install vim
install neovim
install redis
install rcm
install terminal-notifier
install reattach-to-user-namespace
install httpie
install ack
install tree
install awsebcli
install awscli
install exiv2
install heroku/brew/heroku
install git-buildkite
install mkcert
install nginx
install php@7.1
install youtube-dl
install gh
install gpg
brew cask install aws-vault
install starship
install direnv
install bat
install dnsmasq
install pinentry-mac
install exa
